import os
from datetime import datetime


class Reporter:
    def __init__(self, log_file_path=None):
        base_dir = os.path.dirname(os.path.dirname(__file__))
        if log_file_path is None:
            self.log_file_path = os.path.join(base_dir, 'logs', 'usb_audit.log')
        else:
            self.log_file_path = log_file_path
        self.report_dir = os.path.join(base_dir, 'logs')

    def _parse_logs(self, logs):
        """Parse log lines into categorised event buckets."""
        blocked_events    = []
        allowed_events    = []
        spoofed_events    = []
        disconnect_events = []
        file_events       = []

        for line in logs:
            # Enforcer output (actual block command)
            if "Attempting to block" in line or "Successfully blocked device" in line:
                blocked_events.append(line.strip())
            # main.py decision keywords (must match exactly what main.py logs)
            elif "[AUTHORIZED]" in line and "Device allowed" in line:
                allowed_events.append(line.strip())
            elif "[BLOCKLISTED]" in line or "[UNAUTHORIZED]" in line:
                blocked_events.append(line.strip())
            elif "[SPOOF ALERT]" in line or "SPOOFING ALERT" in line:
                spoofed_events.append(line.strip())
            elif "[DISCONNECT]" in line:
                disconnect_events.append(line.strip())
            elif "[FILE" in line:
                file_events.append(line.strip())

        return blocked_events, allowed_events, spoofed_events, disconnect_events, file_events

    def generate_report(self):
        report_path = os.path.join(
            self.report_dir,
            f'usb_security_report_{datetime.now().strftime("%Y%m%d_%H%M%S")}.md'
        )

        try:
            with open(self.log_file_path, 'r', encoding='utf-8', errors='replace') as f:
                logs = f.readlines()
        except FileNotFoundError:
            return "No logs found to generate a report."

        blocked, allowed, spoofed, disconnected, files = self._parse_logs(logs)

        with open(report_path, 'w', encoding='utf-8') as f:
            f.write("# USB Device Control & Monitoring Framework\n")
            f.write("## Security Audit Report\n\n")
            f.write(f"| Field | Value |\n")
            f.write(f"|---|---|\n")
            f.write(f"| Generated On | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} |\n")
            f.write(f"| Total Log Lines Analysed | {len(logs)} |\n")
            f.write(f"| Authorized Connections | {len(allowed)} |\n")
            f.write(f"| Blocked / Unauthorized | {len(blocked)} |\n")
            f.write(f"| Spoofing Alerts | {len(spoofed)} |\n")
            f.write(f"| Disconnections Logged | {len(disconnected)} |\n")
            f.write(f"| File Events Audited | {len(files)} |\n\n")

            # ── Blocked ──────────────────────────────────────────────────
            f.write("---\n\n## 🛑 Blocked / Unauthorized Devices\n\n")
            if not blocked:
                f.write("*No unauthorized devices blocked during this period.*\n\n")
            else:
                for event in blocked:
                    f.write(f"- `{event}`\n")
                f.write("\n")

            # ── Spoofed ──────────────────────────────────────────────────
            f.write("---\n\n## 🚨 Spoofing / BadUSB Alerts\n\n")
            if not spoofed:
                f.write("*No spoofing attempts detected.*\n\n")
            else:
                for event in spoofed:
                    f.write(f"- `{event}`\n")
                f.write("\n")

            # ── Authorized ───────────────────────────────────────────────
            f.write("---\n\n## ✅ Authorized Device Connections\n\n")
            if not allowed:
                f.write("*No authorized devices connected during this period.*\n\n")
            else:
                for event in allowed:
                    f.write(f"- `{event}`\n")
                f.write("\n")

            # ── File Auditing ─────────────────────────────────────────────
            f.write("---\n\n## 📁 File Activity on Authorized Drives\n\n")
            if not files:
                f.write("*No file activity recorded.*\n\n")
            else:
                for event in files:
                    f.write(f"- `{event}`\n")
                f.write("\n")

            # ── Disconnections ────────────────────────────────────────────
            f.write("---\n\n## 🔌 Device Disconnections\n\n")
            if not disconnected:
                f.write("*No disconnect events logged.*\n\n")
            else:
                for event in disconnected:
                    f.write(f"- `{event}`\n")
                f.write("\n")

            f.write("---\n\n*Report generated by USB Device Control & Monitoring Framework.*\n")

        return report_path


if __name__ == "__main__":
    reporter = Reporter()
    path = reporter.generate_report()
    print(f"Report generated at: {path}")
